Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 0
    early_stop_patience: 3
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv3_avazu_x1_20250228:
    model: DCNv3
    dataset_id: avazu_x1_tfrecord
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 5.0e-4
    embedding_regularizer: 0
    batch_size: 25600
    embedding_dim: 4
    num_cross_layers: 3
    use_layer_norm: True
    num_heads: 2
    net_dropout: 0.01
    use_batch_norm: True
    epochs: 10
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DCNv3_avazu_x1_20250506_torch:
    model: DCNv3
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_deep_cross_layers: 4
    num_shallow_cross_layers: 5
    deep_net_dropout: 0
    shallow_net_dropout: 0
    layer_norm: True
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

DCNv3_avazu_x1_20250506_torch_4:
    model: DCNv3
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_deep_cross_layers: 4
    num_shallow_cross_layers: 4
    deep_net_dropout: 0
    shallow_net_dropout: 0
    layer_norm: True
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

DCNv3_avazu_x1_20250506_torch_3:
    model: DCNv3
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_deep_cross_layers: 3
    num_shallow_cross_layers: 4
    deep_net_dropout: 0
    shallow_net_dropout: 0
    layer_norm: True
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

DCNv3_avazu_x1_20250506_torch_6:
    model: DCNv3
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_deep_cross_layers: 6
    num_shallow_cross_layers: 4
    deep_net_dropout: 0
    shallow_net_dropout: 0
    layer_norm: True
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'
