Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv3_avazu_x1_20250228:
    model: DCNv3
    dataset_id: avazu_x1_tfrecord
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    batch_size: 12800
    embedding_dim: 4
    num_cross_layers: 3
    use_layer_norm: True
    num_heads: 2
    net_dropout: 0.01
    use_batch_norm: True
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'
