# =========================================================================
# Copyright (C) 2024. Cloud-Device Recommendation System.
# =========================================================================

"""
Negative Sampler for Training with Pairwise Ranking.

This module provides utilities for sampling negative items during training
when the training data contains only positive examples.

Supports two sampling modes:
- Random: uniform sampling from the entire item pool (default)
- Retrieval-based: sampling from per-user hard negative candidate pools
  generated by the retrieval stage

Optimized for high-throughput batch training.
"""

import logging
import numpy as np
import pandas as pd
from typing import List, Set, Any, Optional, Dict

logger = logging.getLogger(__name__)


class NegativeSampler:
    """
    Samples negative items from the item pool for pairwise ranking training.
    
    Optimized for high-throughput training with:
    - Vectorized batch sampling (no Python loops)
    - Pre-computed numpy arrays for fast lookup
    - Cached feature arrays for GPU transfer
    - Optional per-user candidate pools from retrieval stage
    
    Usage:
        # Random sampling (default)
        sampler = NegativeSampler(item_features_df, item_id_col='cand_item_id')
        neg_item_ids = sampler.sample_negatives_batch(positive_ids, num_negatives=4)
        
        # Retrieval-based sampling
        sampler = NegativeSampler(
            item_features_df, item_id_col='cand_item_id',
        )
    """
    
    def __init__(
        self,
        item_features_df: pd.DataFrame,
        item_id_col: str = 'cand_item_id',
    ):
        """
        Initialize the negative sampler with pre-computed lookup structures.
        
        Args:
            item_features_df: DataFrame containing item features.
            item_id_col: Column name for item IDs
        """
        self.item_id_col = item_id_col

        # Ensure DataFrame is indexed by item_id for fast lookup
        if item_features_df.index.name == item_id_col:
            self.item_features_df = item_features_df
        elif item_id_col in item_features_df.columns:
            self.item_features_df = item_features_df.set_index(item_id_col)
        else:
            # Use first column as index
            self.item_features_df = item_features_df
        
        # Pre-compute numpy arrays for fast sampling
        self.all_item_ids = self.item_features_df.index.to_numpy()
        self.num_items = self.item_features_df.shape[0]
        
        # Build item_id -> index mapping for fast lookup
        self._item_id_to_idx: Optional[Dict] = None
        
        # Per-user candidate pools (loaded from retrieval stage)
        self.user_candidates: Optional[Dict[Any, np.ndarray]] = None
        self.has_user_candidates = False

        logger.info(f"NegativeSampler initialized with {self.num_items} items, "
                   f"{self.item_features_df.shape[1]} feature columns pre-cached"
                   f"{', with per-user candidates' if self.has_user_candidates else ''}")
    
    def sample_negatives_batch(
        self,
        positive_item_ids: np.ndarray,
        num_negatives: int,
    ) -> np.ndarray:
        """
        Sample negative items for a batch, excluding positives.
        
        Optimized version that minimizes Python loops.
        
        Args:
            positive_item_ids: Array of positive item IDs [batch_size]
            num_negatives: Number of negatives per positive
            
        Returns:
            Array of negative item IDs [batch_size, num_negatives]
        """
        batch_size = len(positive_item_ids)
        
        # Sample more than needed to handle collisions
        oversample_factor = 2
        total_samples = num_negatives * oversample_factor
        
        # Random indices into all_item_ids
        sampled_indices = np.random.randint(
            0, self.num_items,
            size=(batch_size, total_samples)
        )
        
        # Get corresponding item IDs
        sampled_ids = self.all_item_ids[sampled_indices]
        
        # Build result array
        result = np.zeros((batch_size, num_negatives), dtype=self.all_item_ids.dtype)
        
        # Vectorized collision check and selection
        for i in range(batch_size):
            pos_id = positive_item_ids[i]
            candidates = sampled_ids[i]
            
            # Filter out positive ID (vectorized)
            valid_mask = candidates != pos_id
            valid_candidates = candidates[valid_mask]
            
            # Take first num_negatives
            if len(valid_candidates) >= num_negatives:
                result[i] = valid_candidates[:num_negatives]
            else:
                # Very rare edge case: pad with any items
                result[i, :len(valid_candidates)] = valid_candidates
                if len(valid_candidates) > 0:
                    result[i, len(valid_candidates):] = valid_candidates[0]
                else:
                    result[i] = self.all_item_ids[:num_negatives]
        
        return result

    def get_features_by_ids(
        self,
        item_ids: np.ndarray,
    ) -> pd.DataFrame:
        """
        Get features for items by their IDs.
        
        Args:
            item_ids: Array of item IDs
            
        Returns:
            pd.DataFrame with item features for the given IDs
        """
        return self.item_features_df.loc[item_ids]
