Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

FiGNN_test:
    model: FiGNN
    dataset_id: tiny_parquet
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    gnn_layers: 2
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

FiGNN_avazu_x1: # This is the model tested on 2025.02.25.
    model: FiGNN
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0.0001
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    gnn_layers: 8
    use_residual: True
    use_gru: False
    reuse_graph_layer: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiGNN_criteo_x1: # This is the model tested on
    model: FiGNN
    dataset_id: criteo_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 0.001
    embedding_regularizer: 1e-5
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    gnn_layers: 6
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

