Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv2_test:
    model: DCNv2
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 40
    stacked_dnn_hidden_units: [64, 32]
    parallel_dnn_hidden_units: [64, 32]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DCNv2_avazu_x1:
    model: DCNv2
    dataset_id: avazu_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: crossnet_only
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0.0001
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 4
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCNv2_criteo_x1:
    model: DCNv2
    dataset_id: criteo_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: crossnet_only
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 0.001
    embedding_regularizer: 1e-5
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 5
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

